from __future__ import annotations

from sqlalchemy import (
    MetaData,
    Table,
    Column,
    String,
    Integer,
    Float,
    Boolean,
    Text,
    DateTime,
    Index,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB


metadata = MetaData()

miners = Table(
    "miners",
    metadata,
    Column("address", String, primary_key=True),
    Column("name", String, nullable=False),
    Column("registration_index", Integer, nullable=False, default=0),
    Column("status", String, nullable=False, default="active"),
    Column("public_key", Text, nullable=False),
    Column("economic_unit_id", String, nullable=False),
    Column("ip_address", String, nullable=True),
    Column("user_agent_hash", String, nullable=True),
    Column("total_rewards", Integer, nullable=False, default=0),
    Column("forecast_commits", Integer, nullable=False, default=0),
    Column("forecast_reveals", Integer, nullable=False, default=0),
    Column("settled_tasks", Integer, nullable=False, default=0),
    Column("correct_direction_count", Integer, nullable=False, default=0),
    Column("edge_score_total", Float, nullable=False, default=0.0),
    Column("held_rewards", Integer, nullable=False, default=0),
    Column("fast_task_opportunities", Integer, nullable=False, default=0),
    Column("fast_task_misses", Integer, nullable=False, default=0),
    Column("fast_window_start_at", DateTime(timezone=True), nullable=True),
    Column("admission_state", String, nullable=False, default="probation"),
    Column("model_reliability", Float, nullable=False, default=1.0),
    Column("ops_reliability", Float, nullable=False, default=1.0),
    Column("arena_multiplier", Float, nullable=False, default=1.0),
    Column("poker_mtt_multiplier", Float, nullable=False, default=1.0),
    Column("poker_mtt_user_id", String, nullable=True),
    Column("poker_mtt_auth_source", String, nullable=True),
    Column("poker_mtt_reward_bound", Boolean, nullable=False, default=False),
    Column("poker_mtt_reward_bound_at", DateTime(timezone=True), nullable=True),
    Column("poker_mtt_is_synthetic", Boolean, nullable=False, default=False),
    Column("poker_mtt_identity_expires_at", DateTime(timezone=True), nullable=True),
    Column("poker_mtt_identity_revoked_at", DateTime(timezone=True), nullable=True),
    Column("public_rank", Integer, nullable=True),
    Column("public_elo", Integer, nullable=False, default=1200),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


forecast_task_runs = Table(
    "forecast_task_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("lane", String, nullable=False),
    Column("asset", String, nullable=False),
    Column("publish_at", DateTime(timezone=True), nullable=False),
    Column("commit_deadline", DateTime(timezone=True), nullable=False),
    Column("reveal_deadline", DateTime(timezone=True), nullable=False),
    Column("resolve_at", DateTime(timezone=True), nullable=False),
    Column("baseline_q_bps", Integer, nullable=False),
    Column("baseline_method", String, nullable=False),
    Column("snapshot_health", String, nullable=False),
    Column("task_state", String, nullable=False, default="reward_eligible"),
    Column("degraded_reason", String, nullable=True),
    Column("void_reason", String, nullable=True),
    Column("resolution_source", String, nullable=True),
    Column("pack_hash", String, nullable=False),
    Column("pack_json", JSONB, nullable=False),
    Column("commit_close_ref_price", Float, nullable=True),
    Column("end_ref_price", Float, nullable=True),
    Column("outcome", Integer, nullable=True),
    Column("reward_window_id", String, nullable=True),
    Column("state", String, nullable=False, default="published"),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


forecast_submissions = Table(
    "forecast_submissions",
    metadata,
    Column("id", String, primary_key=True),
    Column("task_run_id", String, nullable=False),
    Column("miner_address", String, nullable=False),
    Column("economic_unit_id", String, nullable=False),
    Column("commit_request_id", String, nullable=True, unique=True),
    Column("reveal_request_id", String, nullable=True, unique=True),
    Column("commit_hash", String, nullable=False),
    Column("commit_nonce", String, nullable=False),
    Column("p_yes_bps", Integer, nullable=True),
    Column("eligibility_status", String, nullable=False, default="eligible"),
    Column("state", String, nullable=False, default="committed"),
    Column("score", Float, nullable=False, default=0.0),
    Column("reward_amount", Integer, nullable=False, default=0),
    Column("reward_window_id", String, nullable=True),
    Column("accepted_commit_at", DateTime(timezone=True), nullable=False),
    Column("accepted_reveal_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("task_run_id", "miner_address", name="uq_forecast_submission_task_miner"),
)


reward_windows = Table(
    "reward_windows",
    metadata,
    Column("id", String, primary_key=True),
    Column("lane", String, nullable=False),
    Column("state", String, nullable=False, default="finalized"),
    Column("window_start_at", DateTime(timezone=True), nullable=False),
    Column("window_end_at", DateTime(timezone=True), nullable=False),
    Column("task_count", Integer, nullable=False, default=0),
    Column("submission_count", Integer, nullable=False, default=0),
    Column("miner_count", Integer, nullable=False, default=0),
    Column("total_reward_amount", Integer, nullable=False, default=0),
    Column("settlement_batch_id", String, nullable=True),
    Column("policy_bundle_version", String, nullable=False, default="pb_2026_04_09_a"),
    Column("canonical_root", String, nullable=True),
    Column("task_run_ids", JSONB, nullable=False, default=list),
    Column("miner_addresses", JSONB, nullable=False, default=list),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


poker_mtt_budget_ledgers = Table(
    "poker_mtt_budget_ledgers",
    metadata,
    Column("id", String, primary_key=True),
    Column("budget_source_id", String, nullable=False),
    Column("emission_epoch_id", String, nullable=False),
    Column("lane", String, nullable=False),
    Column("reward_window_id", String, nullable=False),
    Column("settlement_batch_id", String, nullable=True),
    Column("window_start_at", DateTime(timezone=True), nullable=False),
    Column("window_end_at", DateTime(timezone=True), nullable=False),
    Column("requested_amount", Integer, nullable=False, default=0),
    Column("approved_amount", Integer, nullable=False, default=0),
    Column("paid_amount", Integer, nullable=False, default=0),
    Column("forfeited_amount", Integer, nullable=False, default=0),
    Column("rolled_amount", Integer, nullable=False, default=0),
    Column("state", String, nullable=False, default="reserved"),
    Column("policy_bundle_version", String, nullable=False),
    Column("budget_root", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_budget_epoch", "budget_source_id", "emission_epoch_id"),
    Index("ix_poker_mtt_budget_reward_window", "reward_window_id"),
)


settlement_batches = Table(
    "settlement_batches",
    metadata,
    Column("id", String, primary_key=True),
    Column("lane", String, nullable=False),
    Column("state", String, nullable=False, default="open"),
    Column("window_start_at", DateTime(timezone=True), nullable=False),
    Column("window_end_at", DateTime(timezone=True), nullable=False),
    Column("reward_window_ids", JSONB, nullable=False, default=list),
    Column("policy_bundle_version", String, nullable=False, default="pb_2026_04_09_a"),
    Column("task_count", Integer, nullable=False, default=0),
    Column("miner_count", Integer, nullable=False, default=0),
    Column("total_reward_amount", Integer, nullable=False, default=0),
    Column("anchor_job_id", String, nullable=True),
    Column("anchor_schema_version", String, nullable=True),
    Column("canonical_root", String, nullable=True),
    Column("anchor_payload_json", JSONB, nullable=True, default=None),
    Column("anchor_payload_hash", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


anchor_jobs = Table(
    "anchor_jobs",
    metadata,
    Column("id", String, primary_key=True),
    Column("settlement_batch_id", String, nullable=False),
    Column("lane", String, nullable=False),
    Column("state", String, nullable=False, default="anchor_submitted"),
    Column("anchor_payload_hash", String, nullable=False),
    Column("broadcast_status", String, nullable=True),
    Column("broadcast_tx_hash", String, nullable=True),
    Column("chain_confirmation_status", String, nullable=True),
    Column("last_broadcast_at", DateTime(timezone=True), nullable=True),
    Column("failure_reason", Text, nullable=True),
    Column("submitted_at", DateTime(timezone=True), nullable=False),
    Column("anchored_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


artifacts = Table(
    "artifacts",
    metadata,
    Column("id", String, primary_key=True),
    Column("kind", String, nullable=False),
    Column("entity_type", String, nullable=False),
    Column("entity_id", String, nullable=False),
    Column("payload_json", JSONB, nullable=False),
    Column("payload_hash", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_artifacts_entity_kind_id", "entity_type", "entity_id", "kind"),
)


reward_hold_entries = Table(
    "reward_hold_entries",
    metadata,
    Column("id", String, primary_key=True),
    Column("miner_address", String, nullable=False),
    Column("task_run_id", String, nullable=False),
    Column("submission_id", String, nullable=False),
    Column("amount_held", Integer, nullable=False, default=0),
    Column("amount_released", Integer, nullable=False, default=0),
    Column("state", String, nullable=False, default="held"),
    Column("release_after", DateTime(timezone=True), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


risk_review_cases = Table(
    "risk_review_cases",
    metadata,
    Column("id", String, primary_key=True),
    Column("case_type", String, nullable=False),
    Column("severity", String, nullable=False, default="medium"),
    Column("state", String, nullable=False, default="open"),
    Column("economic_unit_id", String, nullable=False),
    Column("miner_address", String, nullable=True),
    Column("task_run_id", String, nullable=True),
    Column("submission_id", String, nullable=True),
    Column("decision", String, nullable=True),
    Column("decision_reason", Text, nullable=True),
    Column("reviewed_by", String, nullable=True),
    Column("authority_level", String, nullable=True),
    Column("trace_id", String, nullable=True),
    Column("override_log_id", String, nullable=True),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column("evidence_json", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


arena_result_entries = Table(
    "arena_result_entries",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("miner_address", String, nullable=False),
    Column("rated_or_practice", String, nullable=False),
    Column("human_only", Boolean, nullable=False, default=True),
    Column("eligible_for_multiplier", Boolean, nullable=False, default=False),
    Column("arena_score", Float, nullable=False),
    Column("conservative_skill", Float, nullable=True),
    Column("multiplier_after", Float, nullable=False, default=1.0),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


poker_mtt_tournaments = Table(
    "poker_mtt_tournaments",
    metadata,
    Column("id", String, primary_key=True),
    Column("runtime_source", String, nullable=False, default="lepoker-gameserver"),
    Column("rated_or_practice", String, nullable=False),
    Column("human_only", Boolean, nullable=False, default=True),
    Column("field_size", Integer, nullable=False),
    Column("buy_in_tier", String, nullable=True),
    Column("structure_version", String, nullable=True),
    Column("status", String, nullable=False, default="completed"),
    Column("policy_bundle_version", String, nullable=False, default="poker_mtt_v1"),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("completed_at", DateTime(timezone=True), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


poker_mtt_hand_events = Table(
    "poker_mtt_hand_events",
    metadata,
    Column("hand_id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("table_id", String, nullable=False),
    Column("hand_no", Integer, nullable=False),
    Column("version", Integer, nullable=True),
    Column("checksum", String, nullable=False),
    Column("event_id", String, nullable=False),
    Column("source_json", JSONB, nullable=False),
    Column("payload_json", JSONB, nullable=False),
    Column("ingest_state", String, nullable=False, default="inserted"),
    Column("conflict_reason", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_hand_events_tournament_hand_no", "tournament_id", "hand_no"),
    Index("ix_poker_mtt_hand_events_tournament_ingest_state", "tournament_id", "ingest_state"),
    Index("ix_poker_mtt_hand_events_table_hand_no", "table_id", "hand_no"),
)


poker_mtt_mq_checkpoints = Table(
    "poker_mtt_mq_checkpoints",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=True),
    Column("topic", String, nullable=False),
    Column("queue", String, nullable=False),
    Column("consumer_group", String, nullable=False),
    Column("last_offset", Integer, nullable=True),
    Column("last_message_id", String, nullable=True),
    Column("last_biz_id", String, nullable=True),
    Column("last_hand_id", String, nullable=True),
    Column("last_ingest_state", String, nullable=False),
    Column("replay_root", String, nullable=False),
    Column("lag_messages", Integer, nullable=False, default=0),
    Column("lag_watermark_at", DateTime(timezone=True), nullable=True),
    Column("source_json", JSONB, nullable=False, default=dict),
    Column("last_processed_at", DateTime(timezone=True), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_mq_checkpoints_tournament", "tournament_id"),
    Index("ix_poker_mtt_mq_checkpoints_group_queue", "topic", "consumer_group", "queue"),
)


poker_mtt_mq_conflicts = Table(
    "poker_mtt_mq_conflicts",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=True),
    Column("hand_id", String, nullable=True),
    Column("topic", String, nullable=False),
    Column("queue", String, nullable=False),
    Column("consumer_group", String, nullable=False),
    Column("offset", Integer, nullable=True),
    Column("message_id", String, nullable=True),
    Column("biz_id", String, nullable=True),
    Column("version", Integer, nullable=True),
    Column("checksum", String, nullable=True),
    Column("previous_checksum", String, nullable=True),
    Column("conflict_reason", String, nullable=False),
    Column("state", String, nullable=False, default="manual_review"),
    Column("payload_json", JSONB, nullable=False, default=dict),
    Column("previous_payload_json", JSONB, nullable=True),
    Column("source_json", JSONB, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_mq_conflicts_tournament_state", "tournament_id", "state"),
    Index("ix_poker_mtt_mq_conflicts_hand", "hand_id"),
)


poker_mtt_mq_dlq = Table(
    "poker_mtt_mq_dlq",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=True),
    Column("topic", String, nullable=False),
    Column("queue", String, nullable=False),
    Column("consumer_group", String, nullable=False),
    Column("offset", Integer, nullable=True),
    Column("message_id", String, nullable=True),
    Column("biz_id", String, nullable=True),
    Column("dlq_reason", String, nullable=False),
    Column("state", String, nullable=False, default="open"),
    Column("payload_json", JSONB, nullable=False, default=dict),
    Column("source_json", JSONB, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_mq_dlq_tournament_state", "tournament_id", "state"),
    Index("ix_poker_mtt_mq_dlq_group_queue", "topic", "consumer_group", "queue"),
)


poker_mtt_short_term_hud_snapshots = Table(
    "poker_mtt_short_term_hud_snapshots",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("miner_address", String, nullable=False),
    Column("source_user_id", String, nullable=True),
    Column("hud_window", String, nullable=False, default="short_term"),
    Column("hands_seen", Integer, nullable=False, default=0),
    Column("metrics_json", JSONB, nullable=False, default=dict),
    Column("policy_bundle_version", String, nullable=False),
    Column("manifest_root", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_short_hud_tournament_miner", "tournament_id", "miner_address"),
    Index("ix_poker_mtt_short_hud_miner_updated", "miner_address", "updated_at"),
)


poker_mtt_long_term_hud_snapshots = Table(
    "poker_mtt_long_term_hud_snapshots",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("miner_address", String, nullable=False),
    Column("source_user_id", String, nullable=True),
    Column("hud_window", String, nullable=False, default="long_term"),
    Column("hands_seen", Integer, nullable=False, default=0),
    Column("metrics_json", JSONB, nullable=False, default=dict),
    Column("policy_bundle_version", String, nullable=False),
    Column("manifest_root", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_long_hud_tournament_miner", "tournament_id", "miner_address"),
    Index("ix_poker_mtt_long_hud_miner_updated", "miner_address", "updated_at"),
)


poker_mtt_hidden_eval_entries = Table(
    "poker_mtt_hidden_eval_entries",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("miner_address", String, nullable=False),
    Column("final_ranking_id", String, nullable=False),
    Column("seed_assignment_id", String, nullable=False),
    Column("baseline_sample_id", String, nullable=True),
    Column("hidden_eval_score", Float, nullable=False, default=0.0),
    Column("score_components_json", JSONB, nullable=False, default=dict),
    Column("evidence_root", String, nullable=False),
    Column("manifest_root", String, nullable=False),
    Column("policy_bundle_version", String, nullable=False),
    Column("visibility_state", String, nullable=False, default="service_internal"),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_hidden_eval_tournament_miner", "tournament_id", "miner_address"),
    Index("ix_poker_mtt_hidden_eval_final_ranking", "final_ranking_id"),
)


poker_mtt_rating_snapshots = Table(
    "poker_mtt_rating_snapshots",
    metadata,
    Column("id", String, primary_key=True),
    Column("miner_address", String, nullable=False),
    Column("window_start_at", DateTime(timezone=True), nullable=False),
    Column("window_end_at", DateTime(timezone=True), nullable=False),
    Column("public_rating", Float, nullable=False),
    Column("public_rank", Integer, nullable=True),
    Column("confidence", Float, nullable=False, default=0.0),
    Column("policy_bundle_version", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_rating_miner_window", "miner_address", "window_end_at"),
)


poker_mtt_multiplier_snapshots = Table(
    "poker_mtt_multiplier_snapshots",
    metadata,
    Column("id", String, primary_key=True),
    Column("miner_address", String, nullable=False),
    Column("source_result_id", String, nullable=False),
    Column("multiplier_before", Float, nullable=False),
    Column("multiplier_after", Float, nullable=False),
    Column("rolling_score", Float, nullable=True),
    Column("effective_window_start_at", DateTime(timezone=True), nullable=True),
    Column("effective_window_end_at", DateTime(timezone=True), nullable=True),
    Column("policy_bundle_version", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_multiplier_miner_updated", "miner_address", "updated_at"),
    Index("ix_poker_mtt_multiplier_source_result", "source_result_id"),
)


poker_mtt_corrections = Table(
    "poker_mtt_corrections",
    metadata,
    Column("id", String, primary_key=True),
    Column("target_entity_type", String, nullable=False),
    Column("target_entity_id", String, nullable=False),
    Column("previous_root", String, nullable=False),
    Column("corrected_root", String, nullable=False),
    Column("reason", Text, nullable=False),
    Column("operator_id", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_corrections_target", "target_entity_type", "target_entity_id"),
)


poker_mtt_final_rankings = Table(
    "poker_mtt_final_rankings",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("source_mtt_id", String, nullable=False),
    Column("source_user_id", String, nullable=True),
    Column("miner_address", String, nullable=True),
    Column("economic_unit_id", String, nullable=True),
    Column("member_id", String, nullable=False),
    Column("entry_number", Integer, nullable=False, default=0),
    Column("reentry_count", Integer, nullable=False, default=1),
    Column("rank", Integer, nullable=True),
    Column("rank_state", String, nullable=False),
    Column("chip", Float, nullable=False, default=0.0),
    Column("chip_delta", Float, nullable=False, default=0.0),
    Column("died_time", String, nullable=True),
    Column("waiting_or_no_show", Boolean, nullable=False, default=False),
    Column("bounty", Float, nullable=False, default=0.0),
    Column("defeat_num", Integer, nullable=False, default=0),
    Column("field_size_policy", String, nullable=False),
    Column("standing_snapshot_id", String, nullable=False),
    Column("standing_snapshot_hash", String, nullable=False),
    Column("evidence_root", String, nullable=True),
    Column("evidence_state", String, nullable=False, default="pending"),
    Column("policy_bundle_version", String, nullable=False),
    Column("snapshot_found", Boolean, nullable=False, default=True),
    Column("status", String, nullable=False),
    Column("player_name", String, nullable=True),
    Column("room_id", String, nullable=True),
    Column("start_chip", Float, nullable=False, default=0.0),
    Column("stand_up_status", String, nullable=True),
    Column("source_rank", String, nullable=True),
    Column("source_rank_numeric", Boolean, nullable=False, default=False),
    Column("zset_score", Float, nullable=True),
    Column("locked_at", DateTime(timezone=True), nullable=True),
    Column("anchorable_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("tournament_id", "member_id", name="uq_poker_mtt_final_ranking_tournament_member"),
    Index("ix_poker_mtt_final_rankings_window_join", "id", "tournament_id", "miner_address", "policy_bundle_version"),
)


poker_mtt_result_entries = Table(
    "poker_mtt_result_entries",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("miner_address", String, nullable=False),
    Column("economic_unit_id", String, nullable=True),
    Column("rated_or_practice", String, nullable=False),
    Column("human_only", Boolean, nullable=False, default=True),
    Column("field_size", Integer, nullable=False),
    Column("final_rank", Integer, nullable=False),
    Column("entry_number", Integer, nullable=True),
    Column("reentry_count", Integer, nullable=False, default=1),
    Column("finish_percentile", Float, nullable=False),
    Column("tournament_result_score", Float, nullable=False),
    Column("hidden_eval_score", Float, nullable=False, default=0.0),
    Column("consistency_input_score", Float, nullable=False, default=0.0),
    Column("total_score", Float, nullable=False),
    Column("eligible_for_multiplier", Boolean, nullable=False, default=False),
    Column("rolling_score", Float, nullable=True),
    Column("multiplier_before", Float, nullable=False, default=1.0),
    Column("multiplier_after", Float, nullable=False, default=1.0),
    Column("evaluation_state", String, nullable=False, default="provisional"),
    Column("evaluation_version", String, nullable=False, default="poker_mtt_v1"),
    Column("rank_state", String, nullable=True),
    Column("chip_delta", Float, nullable=True),
    Column("final_ranking_id", String, nullable=True),
    Column("standing_snapshot_id", String, nullable=True),
    Column("standing_snapshot_hash", String, nullable=True),
    Column("evidence_root", String, nullable=True),
    Column("evidence_state", String, nullable=False, default="pending"),
    Column("locked_at", DateTime(timezone=True), nullable=True),
    Column("anchorable_at", DateTime(timezone=True), nullable=True),
    Column("anchor_state", String, nullable=False, default="unanchored"),
    Column("anchor_payload_hash", String, nullable=True),
    Column("risk_flags", JSONB, nullable=False, default=list),
    Column("no_multiplier_reason", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_poker_mtt_results_locked_reward_window", "locked_at", "rated_or_practice", "human_only", "evaluation_state"),
    Index(
        "ix_poker_mtt_results_reward_window_ready",
        "locked_at",
        "evaluation_version",
        "evidence_state",
        "rank_state",
        "eligible_for_multiplier",
    ),
    UniqueConstraint("tournament_id", "miner_address", name="uq_poker_mtt_result_tournament_miner"),
)


TABLES = {
    "miners": miners,
    "forecast_task_runs": forecast_task_runs,
    "forecast_submissions": forecast_submissions,
    "reward_windows": reward_windows,
    "poker_mtt_budget_ledgers": poker_mtt_budget_ledgers,
    "settlement_batches": settlement_batches,
    "anchor_jobs": anchor_jobs,
    "artifacts": artifacts,
    "reward_hold_entries": reward_hold_entries,
    "risk_review_cases": risk_review_cases,
    "arena_result_entries": arena_result_entries,
    "poker_mtt_tournaments": poker_mtt_tournaments,
    "poker_mtt_hand_events": poker_mtt_hand_events,
    "poker_mtt_mq_checkpoints": poker_mtt_mq_checkpoints,
    "poker_mtt_mq_conflicts": poker_mtt_mq_conflicts,
    "poker_mtt_mq_dlq": poker_mtt_mq_dlq,
    "poker_mtt_short_term_hud_snapshots": poker_mtt_short_term_hud_snapshots,
    "poker_mtt_long_term_hud_snapshots": poker_mtt_long_term_hud_snapshots,
    "poker_mtt_hidden_eval_entries": poker_mtt_hidden_eval_entries,
    "poker_mtt_rating_snapshots": poker_mtt_rating_snapshots,
    "poker_mtt_multiplier_snapshots": poker_mtt_multiplier_snapshots,
    "poker_mtt_corrections": poker_mtt_corrections,
    "poker_mtt_final_rankings": poker_mtt_final_rankings,
    "poker_mtt_result_entries": poker_mtt_result_entries,
}
