from __future__ import annotations

from sqlalchemy import (
    MetaData,
    Table,
    Column,
    String,
    Integer,
    Float,
    Boolean,
    Text,
    DateTime,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB


metadata = MetaData()

miners = Table(
    "miners",
    metadata,
    Column("address", String, primary_key=True),
    Column("name", String, nullable=False),
    Column("registration_index", Integer, nullable=False, default=0),
    Column("status", String, nullable=False, default="active"),
    Column("public_key", Text, nullable=False),
    Column("economic_unit_id", String, nullable=False),
    Column("ip_address", String, nullable=True),
    Column("user_agent_hash", String, nullable=True),
    Column("total_rewards", Integer, nullable=False, default=0),
    Column("forecast_commits", Integer, nullable=False, default=0),
    Column("forecast_reveals", Integer, nullable=False, default=0),
    Column("settled_tasks", Integer, nullable=False, default=0),
    Column("correct_direction_count", Integer, nullable=False, default=0),
    Column("edge_score_total", Float, nullable=False, default=0.0),
    Column("held_rewards", Integer, nullable=False, default=0),
    Column("fast_task_opportunities", Integer, nullable=False, default=0),
    Column("fast_task_misses", Integer, nullable=False, default=0),
    Column("fast_window_start_at", DateTime(timezone=True), nullable=True),
    Column("admission_state", String, nullable=False, default="probation"),
    Column("model_reliability", Float, nullable=False, default=1.0),
    Column("ops_reliability", Float, nullable=False, default=1.0),
    Column("arena_multiplier", Float, nullable=False, default=1.0),
    Column("poker_mtt_multiplier", Float, nullable=False, default=1.0),
    Column("public_rank", Integer, nullable=True),
    Column("public_elo", Integer, nullable=False, default=1200),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


forecast_task_runs = Table(
    "forecast_task_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("lane", String, nullable=False),
    Column("asset", String, nullable=False),
    Column("publish_at", DateTime(timezone=True), nullable=False),
    Column("commit_deadline", DateTime(timezone=True), nullable=False),
    Column("reveal_deadline", DateTime(timezone=True), nullable=False),
    Column("resolve_at", DateTime(timezone=True), nullable=False),
    Column("baseline_q_bps", Integer, nullable=False),
    Column("baseline_method", String, nullable=False),
    Column("snapshot_health", String, nullable=False),
    Column("task_state", String, nullable=False, default="reward_eligible"),
    Column("degraded_reason", String, nullable=True),
    Column("void_reason", String, nullable=True),
    Column("resolution_source", String, nullable=True),
    Column("pack_hash", String, nullable=False),
    Column("pack_json", JSONB, nullable=False),
    Column("commit_close_ref_price", Float, nullable=True),
    Column("end_ref_price", Float, nullable=True),
    Column("outcome", Integer, nullable=True),
    Column("reward_window_id", String, nullable=True),
    Column("state", String, nullable=False, default="published"),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


forecast_submissions = Table(
    "forecast_submissions",
    metadata,
    Column("id", String, primary_key=True),
    Column("task_run_id", String, nullable=False),
    Column("miner_address", String, nullable=False),
    Column("economic_unit_id", String, nullable=False),
    Column("commit_request_id", String, nullable=True, unique=True),
    Column("reveal_request_id", String, nullable=True, unique=True),
    Column("commit_hash", String, nullable=False),
    Column("commit_nonce", String, nullable=False),
    Column("p_yes_bps", Integer, nullable=True),
    Column("eligibility_status", String, nullable=False, default="eligible"),
    Column("state", String, nullable=False, default="committed"),
    Column("score", Float, nullable=False, default=0.0),
    Column("reward_amount", Integer, nullable=False, default=0),
    Column("reward_window_id", String, nullable=True),
    Column("accepted_commit_at", DateTime(timezone=True), nullable=False),
    Column("accepted_reveal_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("task_run_id", "miner_address", name="uq_forecast_submission_task_miner"),
)


reward_windows = Table(
    "reward_windows",
    metadata,
    Column("id", String, primary_key=True),
    Column("lane", String, nullable=False),
    Column("state", String, nullable=False, default="finalized"),
    Column("window_start_at", DateTime(timezone=True), nullable=False),
    Column("window_end_at", DateTime(timezone=True), nullable=False),
    Column("task_count", Integer, nullable=False, default=0),
    Column("submission_count", Integer, nullable=False, default=0),
    Column("miner_count", Integer, nullable=False, default=0),
    Column("total_reward_amount", Integer, nullable=False, default=0),
    Column("settlement_batch_id", String, nullable=True),
    Column("policy_bundle_version", String, nullable=False, default="pb_2026_04_09_a"),
    Column("canonical_root", String, nullable=True),
    Column("task_run_ids", JSONB, nullable=False, default=list),
    Column("miner_addresses", JSONB, nullable=False, default=list),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


settlement_batches = Table(
    "settlement_batches",
    metadata,
    Column("id", String, primary_key=True),
    Column("lane", String, nullable=False),
    Column("state", String, nullable=False, default="open"),
    Column("window_start_at", DateTime(timezone=True), nullable=False),
    Column("window_end_at", DateTime(timezone=True), nullable=False),
    Column("reward_window_ids", JSONB, nullable=False, default=list),
    Column("policy_bundle_version", String, nullable=False, default="pb_2026_04_09_a"),
    Column("task_count", Integer, nullable=False, default=0),
    Column("miner_count", Integer, nullable=False, default=0),
    Column("total_reward_amount", Integer, nullable=False, default=0),
    Column("anchor_job_id", String, nullable=True),
    Column("anchor_schema_version", String, nullable=True),
    Column("canonical_root", String, nullable=True),
    Column("anchor_payload_json", JSONB, nullable=True, default=None),
    Column("anchor_payload_hash", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


anchor_jobs = Table(
    "anchor_jobs",
    metadata,
    Column("id", String, primary_key=True),
    Column("settlement_batch_id", String, nullable=False),
    Column("lane", String, nullable=False),
    Column("state", String, nullable=False, default="anchor_submitted"),
    Column("anchor_payload_hash", String, nullable=False),
    Column("broadcast_status", String, nullable=True),
    Column("broadcast_tx_hash", String, nullable=True),
    Column("last_broadcast_at", DateTime(timezone=True), nullable=True),
    Column("failure_reason", Text, nullable=True),
    Column("submitted_at", DateTime(timezone=True), nullable=False),
    Column("anchored_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


artifacts = Table(
    "artifacts",
    metadata,
    Column("id", String, primary_key=True),
    Column("kind", String, nullable=False),
    Column("entity_type", String, nullable=False),
    Column("entity_id", String, nullable=False),
    Column("payload_json", JSONB, nullable=False),
    Column("payload_hash", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


reward_hold_entries = Table(
    "reward_hold_entries",
    metadata,
    Column("id", String, primary_key=True),
    Column("miner_address", String, nullable=False),
    Column("task_run_id", String, nullable=False),
    Column("submission_id", String, nullable=False),
    Column("amount_held", Integer, nullable=False, default=0),
    Column("amount_released", Integer, nullable=False, default=0),
    Column("state", String, nullable=False, default="held"),
    Column("release_after", DateTime(timezone=True), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


risk_review_cases = Table(
    "risk_review_cases",
    metadata,
    Column("id", String, primary_key=True),
    Column("case_type", String, nullable=False),
    Column("severity", String, nullable=False, default="medium"),
    Column("state", String, nullable=False, default="open"),
    Column("economic_unit_id", String, nullable=False),
    Column("miner_address", String, nullable=True),
    Column("task_run_id", String, nullable=True),
    Column("submission_id", String, nullable=True),
    Column("decision", String, nullable=True),
    Column("decision_reason", Text, nullable=True),
    Column("reviewed_by", String, nullable=True),
    Column("authority_level", String, nullable=True),
    Column("trace_id", String, nullable=True),
    Column("override_log_id", String, nullable=True),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column("evidence_json", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


arena_result_entries = Table(
    "arena_result_entries",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("miner_address", String, nullable=False),
    Column("rated_or_practice", String, nullable=False),
    Column("human_only", Boolean, nullable=False, default=True),
    Column("eligible_for_multiplier", Boolean, nullable=False, default=False),
    Column("arena_score", Float, nullable=False),
    Column("conservative_skill", Float, nullable=True),
    Column("multiplier_after", Float, nullable=False, default=1.0),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


poker_mtt_tournaments = Table(
    "poker_mtt_tournaments",
    metadata,
    Column("id", String, primary_key=True),
    Column("runtime_source", String, nullable=False, default="lepoker-gameserver"),
    Column("rated_or_practice", String, nullable=False),
    Column("human_only", Boolean, nullable=False, default=True),
    Column("field_size", Integer, nullable=False),
    Column("buy_in_tier", String, nullable=True),
    Column("structure_version", String, nullable=True),
    Column("status", String, nullable=False, default="completed"),
    Column("policy_bundle_version", String, nullable=False, default="poker_mtt_v1"),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("completed_at", DateTime(timezone=True), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)


poker_mtt_final_rankings = Table(
    "poker_mtt_final_rankings",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("source_mtt_id", String, nullable=False),
    Column("source_user_id", String, nullable=True),
    Column("miner_address", String, nullable=True),
    Column("economic_unit_id", String, nullable=True),
    Column("member_id", String, nullable=False),
    Column("entry_number", Integer, nullable=False, default=0),
    Column("reentry_count", Integer, nullable=False, default=1),
    Column("rank", Integer, nullable=True),
    Column("rank_state", String, nullable=False),
    Column("chip", Float, nullable=False, default=0.0),
    Column("chip_delta", Float, nullable=False, default=0.0),
    Column("died_time", String, nullable=True),
    Column("waiting_or_no_show", Boolean, nullable=False, default=False),
    Column("bounty", Float, nullable=False, default=0.0),
    Column("defeat_num", Integer, nullable=False, default=0),
    Column("field_size_policy", String, nullable=False),
    Column("standing_snapshot_id", String, nullable=False),
    Column("standing_snapshot_hash", String, nullable=False),
    Column("evidence_root", String, nullable=True),
    Column("evidence_state", String, nullable=False, default="pending"),
    Column("policy_bundle_version", String, nullable=False),
    Column("snapshot_found", Boolean, nullable=False, default=True),
    Column("status", String, nullable=False),
    Column("player_name", String, nullable=True),
    Column("room_id", String, nullable=True),
    Column("start_chip", Float, nullable=False, default=0.0),
    Column("stand_up_status", String, nullable=True),
    Column("source_rank", String, nullable=True),
    Column("source_rank_numeric", Boolean, nullable=False, default=False),
    Column("zset_score", Float, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("tournament_id", "member_id", name="uq_poker_mtt_final_ranking_tournament_member"),
)


poker_mtt_result_entries = Table(
    "poker_mtt_result_entries",
    metadata,
    Column("id", String, primary_key=True),
    Column("tournament_id", String, nullable=False),
    Column("miner_address", String, nullable=False),
    Column("economic_unit_id", String, nullable=True),
    Column("rated_or_practice", String, nullable=False),
    Column("human_only", Boolean, nullable=False, default=True),
    Column("field_size", Integer, nullable=False),
    Column("final_rank", Integer, nullable=False),
    Column("entry_number", Integer, nullable=True),
    Column("reentry_count", Integer, nullable=False, default=1),
    Column("finish_percentile", Float, nullable=False),
    Column("tournament_result_score", Float, nullable=False),
    Column("hidden_eval_score", Float, nullable=False, default=0.0),
    Column("consistency_input_score", Float, nullable=False, default=0.0),
    Column("total_score", Float, nullable=False),
    Column("eligible_for_multiplier", Boolean, nullable=False, default=False),
    Column("rolling_score", Float, nullable=True),
    Column("multiplier_before", Float, nullable=False, default=1.0),
    Column("multiplier_after", Float, nullable=False, default=1.0),
    Column("evaluation_state", String, nullable=False, default="provisional"),
    Column("evaluation_version", String, nullable=False, default="poker_mtt_v1"),
    Column("final_ranking_id", String, nullable=True),
    Column("standing_snapshot_id", String, nullable=True),
    Column("standing_snapshot_hash", String, nullable=True),
    Column("evidence_root", String, nullable=True),
    Column("evidence_state", String, nullable=False, default="pending"),
    Column("locked_at", DateTime(timezone=True), nullable=True),
    Column("anchor_state", String, nullable=False, default="unanchored"),
    Column("anchor_payload_hash", String, nullable=True),
    Column("risk_flags", JSONB, nullable=False, default=list),
    Column("no_multiplier_reason", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("tournament_id", "miner_address", name="uq_poker_mtt_result_tournament_miner"),
)


TABLES = {
    "miners": miners,
    "forecast_task_runs": forecast_task_runs,
    "forecast_submissions": forecast_submissions,
    "reward_windows": reward_windows,
    "settlement_batches": settlement_batches,
    "anchor_jobs": anchor_jobs,
    "artifacts": artifacts,
    "reward_hold_entries": reward_hold_entries,
    "risk_review_cases": risk_review_cases,
    "arena_result_entries": arena_result_entries,
    "poker_mtt_tournaments": poker_mtt_tournaments,
    "poker_mtt_final_rankings": poker_mtt_final_rankings,
    "poker_mtt_result_entries": poker_mtt_result_entries,
}
