// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clawchain/settlement/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QuerySettlementAnchorRequest struct {
	SettlementBatchID    string   `protobuf:"bytes,1,opt,name=settlement_batch_id,json=settlementBatchId,proto3" json:"settlement_batch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySettlementAnchorRequest) Reset()         { *m = QuerySettlementAnchorRequest{} }
func (m *QuerySettlementAnchorRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySettlementAnchorRequest) ProtoMessage()    {}
func (*QuerySettlementAnchorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b9887092b5da8a, []int{0}
}
func (m *QuerySettlementAnchorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySettlementAnchorRequest.Unmarshal(m, b)
}
func (m *QuerySettlementAnchorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySettlementAnchorRequest.Marshal(b, m, deterministic)
}
func (m *QuerySettlementAnchorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySettlementAnchorRequest.Merge(m, src)
}
func (m *QuerySettlementAnchorRequest) XXX_Size() int {
	return xxx_messageInfo_QuerySettlementAnchorRequest.Size(m)
}
func (m *QuerySettlementAnchorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySettlementAnchorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySettlementAnchorRequest proto.InternalMessageInfo

func (m *QuerySettlementAnchorRequest) GetSettlementBatchID() string {
	if m != nil {
		return m.SettlementBatchID
	}
	return ""
}

type QuerySettlementAnchorResponse struct {
	Anchor               *SettlementAnchor `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QuerySettlementAnchorResponse) Reset()         { *m = QuerySettlementAnchorResponse{} }
func (m *QuerySettlementAnchorResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySettlementAnchorResponse) ProtoMessage()    {}
func (*QuerySettlementAnchorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b9887092b5da8a, []int{1}
}
func (m *QuerySettlementAnchorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySettlementAnchorResponse.Unmarshal(m, b)
}
func (m *QuerySettlementAnchorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySettlementAnchorResponse.Marshal(b, m, deterministic)
}
func (m *QuerySettlementAnchorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySettlementAnchorResponse.Merge(m, src)
}
func (m *QuerySettlementAnchorResponse) XXX_Size() int {
	return xxx_messageInfo_QuerySettlementAnchorResponse.Size(m)
}
func (m *QuerySettlementAnchorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySettlementAnchorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySettlementAnchorResponse proto.InternalMessageInfo

func (m *QuerySettlementAnchorResponse) GetAnchor() *SettlementAnchor {
	if m != nil {
		return m.Anchor
	}
	return nil
}

type SettlementAnchor struct {
	SettlementBatchID    string   `protobuf:"bytes,1,opt,name=settlement_batch_id,json=settlementBatchId,proto3" json:"settlement_batch_id,omitempty"`
	AnchorJobID          string   `protobuf:"bytes,2,opt,name=anchor_job_id,json=anchorJobId,proto3" json:"anchor_job_id,omitempty"`
	Submitter            string   `protobuf:"bytes,3,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Lane                 string   `protobuf:"bytes,4,opt,name=lane,proto3" json:"lane,omitempty"`
	SchemaVersion        string   `protobuf:"bytes,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	PolicyBundleVersion  string   `protobuf:"bytes,6,opt,name=policy_bundle_version,json=policyBundleVersion,proto3" json:"policy_bundle_version,omitempty"`
	CanonicalRoot        string   `protobuf:"bytes,7,opt,name=canonical_root,json=canonicalRoot,proto3" json:"canonical_root,omitempty"`
	AnchorPayloadHash    string   `protobuf:"bytes,8,opt,name=anchor_payload_hash,json=anchorPayloadHash,proto3" json:"anchor_payload_hash,omitempty"`
	RewardWindowIDsRoot  string   `protobuf:"bytes,9,opt,name=reward_window_ids_root,json=rewardWindowIdsRoot,proto3" json:"reward_window_ids_root,omitempty"`
	TaskRunIDsRoot       string   `protobuf:"bytes,10,opt,name=task_run_ids_root,json=taskRunIdsRoot,proto3" json:"task_run_ids_root,omitempty"`
	MinerRewardRowsRoot  string   `protobuf:"bytes,11,opt,name=miner_reward_rows_root,json=minerRewardRowsRoot,proto3" json:"miner_reward_rows_root,omitempty"`
	WindowEndAt          string   `protobuf:"bytes,12,opt,name=window_end_at,json=windowEndAt,proto3" json:"window_end_at,omitempty"`
	TotalRewardAmount    uint64   `protobuf:"varint,13,opt,name=total_reward_amount,json=totalRewardAmount,proto3" json:"total_reward_amount,omitempty"`
	AnchoredAtHeight     int64    `protobuf:"varint,14,opt,name=anchored_at_height,json=anchoredAtHeight,proto3" json:"anchored_at_height,omitempty"`
	AnchoredAtTime       int64    `protobuf:"varint,15,opt,name=anchored_at_time,json=anchoredAtTime,proto3" json:"anchored_at_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettlementAnchor) Reset()         { *m = SettlementAnchor{} }
func (m *SettlementAnchor) String() string { return proto.CompactTextString(m) }
func (*SettlementAnchor) ProtoMessage()    {}
func (*SettlementAnchor) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b9887092b5da8a, []int{2}
}
func (m *SettlementAnchor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettlementAnchor.Unmarshal(m, b)
}
func (m *SettlementAnchor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettlementAnchor.Marshal(b, m, deterministic)
}
func (m *SettlementAnchor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlementAnchor.Merge(m, src)
}
func (m *SettlementAnchor) XXX_Size() int {
	return xxx_messageInfo_SettlementAnchor.Size(m)
}
func (m *SettlementAnchor) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlementAnchor.DiscardUnknown(m)
}

var xxx_messageInfo_SettlementAnchor proto.InternalMessageInfo

func (m *SettlementAnchor) GetSettlementBatchID() string {
	if m != nil {
		return m.SettlementBatchID
	}
	return ""
}

func (m *SettlementAnchor) GetAnchorJobID() string {
	if m != nil {
		return m.AnchorJobID
	}
	return ""
}

func (m *SettlementAnchor) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *SettlementAnchor) GetLane() string {
	if m != nil {
		return m.Lane
	}
	return ""
}

func (m *SettlementAnchor) GetSchemaVersion() string {
	if m != nil {
		return m.SchemaVersion
	}
	return ""
}

func (m *SettlementAnchor) GetPolicyBundleVersion() string {
	if m != nil {
		return m.PolicyBundleVersion
	}
	return ""
}

func (m *SettlementAnchor) GetCanonicalRoot() string {
	if m != nil {
		return m.CanonicalRoot
	}
	return ""
}

func (m *SettlementAnchor) GetAnchorPayloadHash() string {
	if m != nil {
		return m.AnchorPayloadHash
	}
	return ""
}

func (m *SettlementAnchor) GetRewardWindowIDsRoot() string {
	if m != nil {
		return m.RewardWindowIDsRoot
	}
	return ""
}

func (m *SettlementAnchor) GetTaskRunIDsRoot() string {
	if m != nil {
		return m.TaskRunIDsRoot
	}
	return ""
}

func (m *SettlementAnchor) GetMinerRewardRowsRoot() string {
	if m != nil {
		return m.MinerRewardRowsRoot
	}
	return ""
}

func (m *SettlementAnchor) GetWindowEndAt() string {
	if m != nil {
		return m.WindowEndAt
	}
	return ""
}

func (m *SettlementAnchor) GetTotalRewardAmount() uint64 {
	if m != nil {
		return m.TotalRewardAmount
	}
	return 0
}

func (m *SettlementAnchor) GetAnchoredAtHeight() int64 {
	if m != nil {
		return m.AnchoredAtHeight
	}
	return 0
}

func (m *SettlementAnchor) GetAnchoredAtTime() int64 {
	if m != nil {
		return m.AnchoredAtTime
	}
	return 0
}

func init() {
	proto.RegisterType((*QuerySettlementAnchorRequest)(nil), "clawchain.settlement.v1.QuerySettlementAnchorRequest")
	proto.RegisterType((*QuerySettlementAnchorResponse)(nil), "clawchain.settlement.v1.QuerySettlementAnchorResponse")
	proto.RegisterType((*SettlementAnchor)(nil), "clawchain.settlement.v1.SettlementAnchor")
}

func init() {
	proto.RegisterFile("clawchain/settlement/v1/query.proto", fileDescriptor_21b9887092b5da8a)
}

var fileDescriptor_21b9887092b5da8a = []byte{
	// 646 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x5f, 0x6b, 0x13, 0x4d,
	0x14, 0xc6, 0x49, 0xff, 0xbd, 0x6f, 0x27, 0x26, 0x6d, 0x26, 0xb6, 0x5d, 0x4a, 0x25, 0x25, 0x52,
	0x88, 0x20, 0xbb, 0xb4, 0xc5, 0xaa, 0x88, 0x42, 0x42, 0x0b, 0xad, 0x78, 0xa1, 0x6b, 0x51, 0xf0,
	0x66, 0x98, 0xdd, 0x1d, 0xb2, 0x63, 0x77, 0xe7, 0xa4, 0x3b, 0xb3, 0x5d, 0x83, 0x78, 0xe3, 0x57,
	0xf0, 0x13, 0x79, 0xed, 0xa5, 0xf7, 0x41, 0x82, 0x1f, 0x44, 0x76, 0x66, 0x93, 0x0d, 0xb5, 0x11,
	0x04, 0x6f, 0xc2, 0xec, 0xf3, 0x3c, 0xe7, 0x37, 0x67, 0x0f, 0x39, 0x8b, 0xee, 0xfa, 0x11, 0xcd,
	0xfc, 0x90, 0x72, 0xe1, 0x48, 0xa6, 0x54, 0xc4, 0x62, 0x26, 0x94, 0x73, 0xb5, 0xef, 0x5c, 0xa6,
	0x2c, 0x19, 0xda, 0x83, 0x04, 0x14, 0xe0, 0xad, 0x69, 0xc8, 0x2e, 0x43, 0xf6, 0xd5, 0xfe, 0xf6,
	0xed, 0x3e, 0xf4, 0x41, 0x67, 0x9c, 0xfc, 0x64, 0xe2, 0xdb, 0x3b, 0x7d, 0x80, 0x7e, 0xc4, 0x1c,
	0x3a, 0xe0, 0x0e, 0x15, 0x02, 0x14, 0x55, 0x1c, 0x84, 0x34, 0x6e, 0x9b, 0xa1, 0x9d, 0x57, 0x39,
	0xfb, 0xf5, 0x94, 0xd4, 0x15, 0x7e, 0x08, 0x89, 0xcb, 0x2e, 0x53, 0x26, 0x15, 0x3e, 0x41, 0xcd,
	0xf2, 0x12, 0xe2, 0x51, 0xe5, 0x87, 0x84, 0x07, 0x56, 0x65, 0xb7, 0xd2, 0x59, 0xed, 0x6d, 0x8c,
	0x47, 0xad, 0x46, 0x59, 0xd9, 0xcb, 0xdd, 0xb3, 0x63, 0xb7, 0x21, 0xaf, 0x49, 0x41, 0xdb, 0x43,
	0x77, 0xe6, 0x5c, 0x23, 0x07, 0x20, 0x24, 0xc3, 0x5d, 0xb4, 0x42, 0xb5, 0xa2, 0xd1, 0xd5, 0x83,
	0x7b, 0xf6, 0x9c, 0xb7, 0xb4, 0x7f, 0x43, 0x14, 0x85, 0xed, 0x1f, 0xcb, 0x68, 0xfd, 0xba, 0xf9,
	0x8f, 0xfa, 0xc7, 0x87, 0xa8, 0x66, 0x6e, 0x21, 0xef, 0xc1, 0xcb, 0x01, 0x0b, 0x1a, 0xb0, 0x36,
	0x1e, 0xb5, 0xaa, 0xe6, 0xa6, 0xe7, 0xe0, 0x9d, 0x1d, 0xbb, 0x55, 0x3a, 0x7d, 0x08, 0xf0, 0x0e,
	0x5a, 0x95, 0xa9, 0x17, 0x73, 0xa5, 0x58, 0x62, 0x2d, 0xe6, 0x05, 0x6e, 0x29, 0x60, 0x8c, 0x96,
	0x22, 0x2a, 0x98, 0xb5, 0xa4, 0x0d, 0x7d, 0xc6, 0x7b, 0xa8, 0x2e, 0xfd, 0x90, 0xc5, 0x94, 0x5c,
	0xb1, 0x44, 0x72, 0x10, 0xd6, 0xb2, 0x76, 0x6b, 0x46, 0x7d, 0x63, 0x44, 0x7c, 0x80, 0x36, 0x06,
	0x10, 0x71, 0x7f, 0x48, 0xbc, 0x54, 0x04, 0x11, 0x9b, 0xa6, 0x57, 0x74, 0xba, 0x69, 0xcc, 0x9e,
	0xf6, 0x26, 0x35, 0x7b, 0xa8, 0xee, 0x53, 0x01, 0x82, 0xfb, 0x34, 0x22, 0x09, 0x80, 0xb2, 0xfe,
	0x33, 0xe8, 0xa9, 0xea, 0x02, 0x28, 0x6c, 0xa3, 0x66, 0xf1, 0xa2, 0x03, 0x3a, 0x8c, 0x80, 0x06,
	0x24, 0xa4, 0x32, 0xb4, 0xfe, 0xd7, 0xd9, 0x86, 0xb1, 0x5e, 0x1a, 0xe7, 0x94, 0xca, 0x10, 0xbf,
	0x40, 0x9b, 0x09, 0xcb, 0x68, 0x12, 0x90, 0x8c, 0x8b, 0x00, 0x32, 0xc2, 0x03, 0x69, 0xf0, 0xab,
	0x7a, 0x42, 0x5b, 0xe3, 0x51, 0xab, 0xe9, 0xea, 0xc4, 0x5b, 0x1d, 0x38, 0x3b, 0x96, 0xf9, 0x45,
	0x6e, 0x33, 0x99, 0x15, 0x03, 0x2d, 0xe2, 0xa7, 0xa8, 0xa1, 0xa8, 0xbc, 0x20, 0x49, 0x2a, 0x4a,
	0x10, 0xd2, 0x20, 0x3c, 0x1e, 0xb5, 0xea, 0xe7, 0x54, 0x5e, 0xb8, 0xa9, 0x98, 0x30, 0xea, 0xaa,
	0x78, 0x2e, 0xca, 0x0f, 0xd1, 0x66, 0xcc, 0x05, 0x4b, 0x48, 0xd1, 0x52, 0x02, 0x59, 0xc1, 0xa8,
	0x9a, 0xc1, 0x68, 0xd7, 0x74, 0xe3, 0x42, 0x66, 0x8a, 0xda, 0xa8, 0x56, 0xb4, 0xce, 0x44, 0x40,
	0xa8, 0xb2, 0x6e, 0xe9, 0x6c, 0xd5, 0x88, 0x27, 0x22, 0xe8, 0xea, 0xa9, 0x28, 0x50, 0xf9, 0xe0,
	0x0c, 0x98, 0xc6, 0x90, 0x0a, 0x65, 0xd5, 0x76, 0x2b, 0x9d, 0x25, 0xb7, 0xa1, 0x2d, 0x43, 0xed,
	0x6a, 0x03, 0xdf, 0x47, 0xd8, 0x8c, 0x8a, 0xe5, 0x44, 0x12, 0x32, 0xde, 0x0f, 0x95, 0x55, 0xdf,
	0xad, 0x74, 0x16, 0xdd, 0xf5, 0x89, 0xd3, 0x55, 0xa7, 0x5a, 0xc7, 0x1d, 0xb4, 0x3e, 0x9b, 0x56,
	0x3c, 0x66, 0xd6, 0x9a, 0xce, 0xd6, 0xcb, 0xec, 0x39, 0x8f, 0xd9, 0xc1, 0xb7, 0x0a, 0x5a, 0xd6,
	0x7b, 0x84, 0xbf, 0x56, 0x6e, 0xf8, 0xb3, 0x3f, 0x98, 0xbb, 0x34, 0x7f, 0xda, 0xf1, 0xed, 0xa3,
	0xbf, 0x2d, 0x33, 0x3b, 0xdb, 0x7e, 0xf6, 0xf9, 0xfb, 0xcf, 0x2f, 0x0b, 0x8f, 0xf0, 0x91, 0x33,
	0xef, 0xb3, 0x65, 0xda, 0x97, 0xce, 0xc7, 0x1b, 0x76, 0xf0, 0x53, 0xef, 0xf1, 0xbb, 0x87, 0x7d,
	0xae, 0xc2, 0xd4, 0xb3, 0x7d, 0x88, 0x67, 0x18, 0xe5, 0xe9, 0xc3, 0x2c, 0x4f, 0x0d, 0x07, 0x4c,
	0x3e, 0xd1, 0xbf, 0xde, 0x8a, 0xfe, 0x7a, 0x1d, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x77,
	0x22, 0xc2, 0x31, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	SettlementAnchor(ctx context.Context, in *QuerySettlementAnchorRequest, opts ...grpc.CallOption) (*QuerySettlementAnchorResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) SettlementAnchor(ctx context.Context, in *QuerySettlementAnchorRequest, opts ...grpc.CallOption) (*QuerySettlementAnchorResponse, error) {
	out := new(QuerySettlementAnchorResponse)
	err := c.cc.Invoke(ctx, "/clawchain.settlement.v1.Query/SettlementAnchor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	SettlementAnchor(context.Context, *QuerySettlementAnchorRequest) (*QuerySettlementAnchorResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) SettlementAnchor(ctx context.Context, req *QuerySettlementAnchorRequest) (*QuerySettlementAnchorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettlementAnchor not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_SettlementAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySettlementAnchorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SettlementAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clawchain.settlement.v1.Query/SettlementAnchor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SettlementAnchor(ctx, req.(*QuerySettlementAnchorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clawchain.settlement.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SettlementAnchor",
			Handler:    _Query_SettlementAnchor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clawchain/settlement/v1/query.proto",
}
