// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clawchain/settlement/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgAnchorSettlementBatch struct {
	Submitter            string   `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	SettlementBatchId    string   `protobuf:"bytes,2,opt,name=settlement_batch_id,json=settlementBatchId,proto3" json:"settlement_batch_id,omitempty"`
	AnchorJobId          string   `protobuf:"bytes,3,opt,name=anchor_job_id,json=anchorJobId,proto3" json:"anchor_job_id,omitempty"`
	Lane                 string   `protobuf:"bytes,4,opt,name=lane,proto3" json:"lane,omitempty"`
	SchemaVersion        string   `protobuf:"bytes,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	PolicyBundleVersion  string   `protobuf:"bytes,6,opt,name=policy_bundle_version,json=policyBundleVersion,proto3" json:"policy_bundle_version,omitempty"`
	CanonicalRoot        string   `protobuf:"bytes,7,opt,name=canonical_root,json=canonicalRoot,proto3" json:"canonical_root,omitempty"`
	AnchorPayloadHash    string   `protobuf:"bytes,8,opt,name=anchor_payload_hash,json=anchorPayloadHash,proto3" json:"anchor_payload_hash,omitempty"`
	RewardWindowIdsRoot  string   `protobuf:"bytes,9,opt,name=reward_window_ids_root,json=rewardWindowIdsRoot,proto3" json:"reward_window_ids_root,omitempty"`
	TaskRunIdsRoot       string   `protobuf:"bytes,10,opt,name=task_run_ids_root,json=taskRunIdsRoot,proto3" json:"task_run_ids_root,omitempty"`
	MinerRewardRowsRoot  string   `protobuf:"bytes,11,opt,name=miner_reward_rows_root,json=minerRewardRowsRoot,proto3" json:"miner_reward_rows_root,omitempty"`
	WindowEndAt          string   `protobuf:"bytes,12,opt,name=window_end_at,json=windowEndAt,proto3" json:"window_end_at,omitempty"`
	TotalRewardAmount    uint64   `protobuf:"varint,13,opt,name=total_reward_amount,json=totalRewardAmount,proto3" json:"total_reward_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAnchorSettlementBatch) Reset()         { *m = MsgAnchorSettlementBatch{} }
func (m *MsgAnchorSettlementBatch) String() string { return proto.CompactTextString(m) }
func (*MsgAnchorSettlementBatch) ProtoMessage()    {}
func (*MsgAnchorSettlementBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_923d0c7131271a7b, []int{0}
}
func (m *MsgAnchorSettlementBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAnchorSettlementBatch.Unmarshal(m, b)
}
func (m *MsgAnchorSettlementBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAnchorSettlementBatch.Marshal(b, m, deterministic)
}
func (m *MsgAnchorSettlementBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchorSettlementBatch.Merge(m, src)
}
func (m *MsgAnchorSettlementBatch) XXX_Size() int {
	return xxx_messageInfo_MsgAnchorSettlementBatch.Size(m)
}
func (m *MsgAnchorSettlementBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchorSettlementBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchorSettlementBatch proto.InternalMessageInfo

type MsgAnchorSettlementBatchResponse struct {
	SettlementBatchId    string   `protobuf:"bytes,1,opt,name=settlement_batch_id,json=settlementBatchId,proto3" json:"settlement_batch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAnchorSettlementBatchResponse) Reset()         { *m = MsgAnchorSettlementBatchResponse{} }
func (m *MsgAnchorSettlementBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAnchorSettlementBatchResponse) ProtoMessage()    {}
func (*MsgAnchorSettlementBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_923d0c7131271a7b, []int{1}
}
func (m *MsgAnchorSettlementBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAnchorSettlementBatchResponse.Unmarshal(m, b)
}
func (m *MsgAnchorSettlementBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAnchorSettlementBatchResponse.Marshal(b, m, deterministic)
}
func (m *MsgAnchorSettlementBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchorSettlementBatchResponse.Merge(m, src)
}
func (m *MsgAnchorSettlementBatchResponse) XXX_Size() int {
	return xxx_messageInfo_MsgAnchorSettlementBatchResponse.Size(m)
}
func (m *MsgAnchorSettlementBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchorSettlementBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchorSettlementBatchResponse proto.InternalMessageInfo

func (m *MsgAnchorSettlementBatchResponse) GetSettlementBatchId() string {
	if m != nil {
		return m.SettlementBatchId
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgAnchorSettlementBatch)(nil), "clawchain.settlement.v1.MsgAnchorSettlementBatch")
	proto.RegisterType((*MsgAnchorSettlementBatchResponse)(nil), "clawchain.settlement.v1.MsgAnchorSettlementBatchResponse")
}

func init() { proto.RegisterFile("clawchain/settlement/v1/tx.proto", fileDescriptor_923d0c7131271a7b) }

var fileDescriptor_923d0c7131271a7b = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6a, 0xdb, 0x30,
	0x18, 0xc7, 0xeb, 0x35, 0xed, 0x56, 0x75, 0x29, 0xc4, 0x6d, 0x53, 0x2f, 0x97, 0x86, 0x40, 0xa1,
	0x2b, 0xcc, 0x26, 0x0d, 0x6c, 0x74, 0x3b, 0x25, 0x30, 0x58, 0x06, 0x85, 0xe1, 0xc2, 0x06, 0xbb,
	0x08, 0xd9, 0x12, 0xb6, 0x36, 0x5b, 0x5f, 0x90, 0xe4, 0xb8, 0xb9, 0x8d, 0xc1, 0x60, 0x0f, 0xb0,
	0x07, 0xe8, 0x23, 0xf4, 0xb0, 0x27, 0xd9, 0x4b, 0x74, 0x97, 0xbd, 0xc3, 0xb0, 0xe4, 0xc4, 0x1b,
	0x2c, 0x87, 0x5d, 0x8c, 0xfc, 0xfd, 0xfe, 0xfa, 0x7f, 0x7f, 0x89, 0x4f, 0xa8, 0x1f, 0x67, 0xa4,
	0x8c, 0x53, 0xc2, 0x45, 0xa0, 0x98, 0xd6, 0x19, 0xcb, 0x99, 0xd0, 0xc1, 0x7c, 0x18, 0xe8, 0x6b,
	0x7f, 0x26, 0x41, 0x83, 0x7b, 0xb4, 0x52, 0xf8, 0x8d, 0xc2, 0x9f, 0x0f, 0x7b, 0x07, 0x09, 0x24,
	0x60, 0x34, 0x41, 0xb5, 0xb2, 0xf2, 0xde, 0xa3, 0x18, 0x54, 0x0e, 0x0a, 0x5b, 0x60, 0x7f, 0x6a,
	0x74, 0x64, 0xff, 0x82, 0x5c, 0x25, 0x55, 0x87, 0x5c, 0x25, 0x16, 0x0c, 0x7e, 0xb5, 0x90, 0x77,
	0xa9, 0x92, 0xb1, 0x88, 0x53, 0x90, 0x57, 0xab, 0x26, 0x13, 0xa2, 0xe3, 0xd4, 0x7d, 0x8a, 0x76,
	0x54, 0x11, 0xe5, 0x5c, 0x6b, 0x26, 0x3d, 0xa7, 0xef, 0x9c, 0xee, 0x4c, 0xbc, 0x1f, 0xdf, 0x9f,
	0x1c, 0xd4, 0xd6, 0x63, 0x4a, 0x25, 0x53, 0xea, 0x4a, 0x4b, 0x2e, 0x92, 0xb0, 0x91, 0xba, 0x3e,
	0xda, 0x6f, 0xf2, 0xe2, 0xa8, 0xf2, 0xc2, 0x9c, 0x7a, 0xf7, 0x2a, 0x87, 0xb0, 0xa3, 0xfe, 0xee,
	0x32, 0xa5, 0xee, 0x00, 0xb5, 0x89, 0x09, 0x80, 0x3f, 0x40, 0x54, 0x29, 0x37, 0x8d, 0x72, 0xd7,
	0x16, 0x5f, 0x43, 0x34, 0xa5, 0xae, 0x8b, 0x5a, 0x19, 0x11, 0xcc, 0x6b, 0x19, 0x64, 0xd6, 0xee,
	0x09, 0xda, 0x53, 0x71, 0xca, 0x72, 0x82, 0xe7, 0x4c, 0x2a, 0x0e, 0xc2, 0xdb, 0x32, 0xb4, 0x6d,
	0xab, 0x6f, 0x6d, 0xd1, 0x3d, 0x47, 0x87, 0x33, 0xc8, 0x78, 0xbc, 0xc0, 0x51, 0x21, 0x68, 0xc6,
	0x56, 0xea, 0x6d, 0xa3, 0xde, 0xb7, 0x70, 0x62, 0xd8, 0x72, 0xcf, 0x09, 0xda, 0x8b, 0x89, 0x00,
	0xc1, 0x63, 0x92, 0x61, 0x09, 0xa0, 0xbd, 0xfb, 0xd6, 0x7a, 0x55, 0x0d, 0x01, 0x74, 0x75, 0xd2,
	0x3a, 0xf9, 0x8c, 0x2c, 0x32, 0x20, 0x14, 0xa7, 0x44, 0xa5, 0xde, 0x03, 0x7b, 0x52, 0x8b, 0xde,
	0x58, 0xf2, 0x8a, 0xa8, 0xd4, 0x1d, 0xa1, 0xae, 0x64, 0x25, 0x91, 0x14, 0x97, 0x5c, 0x50, 0x28,
	0x31, 0xa7, 0xca, 0xda, 0xef, 0xd8, 0x2c, 0x96, 0xbe, 0x33, 0x70, 0x4a, 0x95, 0x69, 0xf2, 0x18,
	0x75, 0x34, 0x51, 0x1f, 0xb1, 0x2c, 0x44, 0xa3, 0x47, 0x46, 0xbf, 0x57, 0x81, 0xb0, 0x10, 0x4b,
	0xe9, 0x08, 0x75, 0x73, 0x2e, 0x98, 0xc4, 0x75, 0x17, 0x09, 0x65, 0xad, 0xdf, 0xb5, 0xfe, 0x86,
	0x86, 0x06, 0x86, 0x50, 0xda, 0x4d, 0x03, 0xd4, 0xae, 0xd3, 0x30, 0x41, 0x31, 0xd1, 0xde, 0x43,
	0x7b, 0xfd, 0xb6, 0xf8, 0x52, 0xd0, 0xb1, 0x39, 0xa8, 0x06, 0x5d, 0xdd, 0x85, 0x35, 0x26, 0x39,
	0x14, 0x42, 0x7b, 0xed, 0xbe, 0x73, 0xda, 0x0a, 0x3b, 0x06, 0x59, 0xd7, 0xb1, 0x01, 0xcf, 0xbb,
	0x5f, 0x6f, 0x8e, 0x37, 0x7e, 0xde, 0x1c, 0x6f, 0x7c, 0xbe, 0xbb, 0x3d, 0x6b, 0x46, 0x63, 0x10,
	0xa2, 0xfe, 0xba, 0x71, 0x0b, 0x99, 0x9a, 0x81, 0x50, 0x6c, 0xdd, 0xf8, 0x38, 0x6b, 0xc6, 0xe7,
	0xfc, 0x9b, 0x83, 0x36, 0x2f, 0x55, 0xe2, 0x7e, 0x71, 0xd0, 0xe1, 0xbf, 0x07, 0x79, 0xe8, 0xaf,
	0x79, 0x49, 0xfe, 0xba, 0x30, 0xbd, 0x8b, 0xff, 0xde, 0xb2, 0xcc, 0xdf, 0xdb, 0xfa, 0x74, 0x77,
	0x7b, 0xe6, 0x4c, 0x2e, 0xde, 0x3f, 0x4b, 0xb8, 0x4e, 0x8b, 0xc8, 0x8f, 0x21, 0x0f, 0x9a, 0xc7,
	0xde, 0xac, 0xae, 0xff, 0x7c, 0xf8, 0x7a, 0x31, 0x63, 0xea, 0x85, 0xf9, 0x46, 0xdb, 0xe6, 0x71,
	0x8e, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xc2, 0xc9, 0x02, 0x23, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	AnchorSettlementBatch(ctx context.Context, in *MsgAnchorSettlementBatch, opts ...grpc.CallOption) (*MsgAnchorSettlementBatchResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AnchorSettlementBatch(ctx context.Context, in *MsgAnchorSettlementBatch, opts ...grpc.CallOption) (*MsgAnchorSettlementBatchResponse, error) {
	out := new(MsgAnchorSettlementBatchResponse)
	err := c.cc.Invoke(ctx, "/clawchain.settlement.v1.Msg/AnchorSettlementBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AnchorSettlementBatch(context.Context, *MsgAnchorSettlementBatch) (*MsgAnchorSettlementBatchResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AnchorSettlementBatch(ctx context.Context, req *MsgAnchorSettlementBatch) (*MsgAnchorSettlementBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnchorSettlementBatch not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AnchorSettlementBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAnchorSettlementBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AnchorSettlementBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clawchain.settlement.v1.Msg/AnchorSettlementBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AnchorSettlementBatch(ctx, req.(*MsgAnchorSettlementBatch))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clawchain.settlement.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnchorSettlementBatch",
			Handler:    _Msg_AnchorSettlementBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clawchain/settlement/v1/tx.proto",
}
